# This is default and very simple configuration file for Yasb. 
# For more information about configuration options, please visit the Wiki https://github.com/amnweb/yasb/wiki
watch_stylesheet: true
watch_config: true
debug: false
update_check: true # Enable automatic update check.
# komorebi:
#   start_command: "komorebic start --whkd"
#   stop_command: "komorebic stop --whkd"
#   reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["DELL P2720DC"]
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
      center: false
    animation:
      enabled: true
      duration: 400
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: false
      round_corners: false
      round_corners_type: "normal"
      border_color: "system"
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left:
      - "home"
      # - "taskbar"
      # - "komorebi_workspaces"
      # - "komorebi_active_layout"
      - "active_window"
      center:
      # - "clock"
      right:
      - "media"
      - "weather"
      - "systray"
      # - "microphone"
      # - "volume"
      - "notifications"
      - "clock"
      # - "power_menu"
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>üëæ</span>"
      menu_list: []
      # - { title: "User Home", path: "~" }
      # - { title: "Download", path: "~\\Downloads" }
      # - { title: "Documents", path: "~\\Documents" }
      # - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: false
      blur: false
  # taskbar:
  #   type: "yasb.taskbar.TaskbarWidget"
  #   options:
  #     icon_size: 16
  #     tooltip: true
  #     show_only_visible: false
  #     strict_filtering: true
  #     monitor_exclusive: false
  #     animation:
  #       enabled: true
  #     preview:
  #       enabled: false
  #       width: 240
  #       delay: 400
  #       padding: 8
  #       margin: 8
  #     title_label:
  #       enabled: false
  #       show: "always"
  #       min_length: 10
  #       max_length: 30
  #     ignore_apps:
  #       processes: []
  #       titles: []
  #       classes: []
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{artist} - {title}"
      label_alt: "{artist} - {title}"
      max_field_size:
        label: 18
        label_alt: 24
      show_thumbnail: true
      controls_only: false
      controls_left: true
      controls_hide: true
      hide_empty: true
      thumbnail_alpha: 100
      thumbnail_padding: 16
      thumbnail_corner_radius: 0
      thumbnail_edge_fade: true
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      media_menu_icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      media_menu:
        blur: false
        round_corners: false
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 100
        max_title_size: 80
        max_artist_size: 20
        show_source: true
      label_shadow:
        enabled: true
        color: "#000000"
        radius: 2
        offset: [ 1, 1 ]
      scrolling_label:
        enabled: true
        update_interval_ms: 50
        style: "left"  # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 1
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      # label: "{win[title]}"
      label: " "
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 30
      max_length_ellipsis: "..."
      monitor_exclusive: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      # We create a specific class 'clock-bracket' and 'clock-sep' for styling
      label: "<span class='clock-bracket'>[</span> {%A, %d} <span class='clock-sep'>|</span> {%H:%M} <span class='clock-bracket'>]</span>"
      label_alt: "{%A, %d %B %Y %H:%M}"
      timezones: []
      calendar: 
        blur: false
        round_corners: false
        alignment: "center"
        direction: "down"
        show_holidays: true
        country_code: "HR"
        # holiday_color: "#e8ff64ff"
      callbacks:
        on_left: "toggle_calendar"
        on_right: "toggle_label"
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "‚ù∞"
      label_expanded: "‚ù±"
      label_position: "left" # Can be "left" or "right"
      icon_size: 16 # Can be any integer between 8 and 64
      pin_click_modifier: "alt" # Can be "ctrl", "alt" or "shift"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      # btn_shadow:
      #   enabled: true
      #   color: "black"
      #   radius: 3
      #   offset: [ 1, 1 ]
  # komorebi_workspaces:
  #   type: "komorebi.workspaces.WorkspaceWidget"
  #   options:
  #     label_offline: "\u23fc Offline"
  #     label_workspace_btn: "\u000d"
  #     label_workspace_active_btn: "\u000d"
  #     label_workspace_populated_btn: "\u000d"
  #     label_default_name: "{index}"
  #     label_zero_index: false
  #     hide_empty_workspaces: false
  #     hide_if_offline: true
  #     animation: true
  # komorebi_active_layout:
  #   type: "komorebi.active_layout.ActiveLayoutWidget"
  #   options:
  #     hide_if_offline: true
  #     label: "{icon}"
  #     layouts:
  #       [
  #         "bsp",
  #         "columns",
  #         "rows",
  #         "grid",
  #         "vertical_stack",
  #         "horizontal_stack",
  #         "ultrawide_vertical_stack",
  #         "right_main_vertical_stack",
  #       ]
  #     layout_icons:
  #       bsp: "BSP"
  #       columns: "COLS"
  #       rows: "ROWS"
  #       grid: "GRID"
  #       vertical_stack: "V-STACK"
  #       horizontal_stack: "H-STACK"
  #       ultrawide_vertical_stack: "W-STACK"
  #       right_main_vertical_stack: "RMV-STACK"
  #       monocle: "MONOCLE"
  #       maximized: "MAX"
  #       floating: "FLOATING"
  #       paused: "PAUSED"
  #     callbacks:
  #       on_left: "next_layout"
  #       on_middle: "toggle_monocle"
  #       on_right: "prev_layout"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: env
      update_interval: 600
      hide_decimal: true
      location: env
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\ue312"
        cloudyNight: "\ue311"
        rainyDay: "\ue308"
        rainyNight: "\ue333"
        snowyDay: "\ue30a"
        snowyNight: "\ue335"
        blizzardDay: "\udb83\udf36"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card:
        blur: false
        round_corners: false
        alignment: "right"
        direction: "down"
        icon_size: 64
        show_hourly_forecast: true
        time_format: "24h"
        hourly_point_spacing: 76
        hourly_icon_size: 32
        icon_smoothing: true
        temp_line_width: 2
        current_line_color: "#8EAEE8"
        current_line_width: 1
        current_line_style: "dot"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      tooltip: false
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_mute"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "<span>{icon}</span> {level}%"
      icons:
        normal: "\udb80\udf6c"
        muted: "\udb80\udf6d"
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 200
      button_row: 5
      buttons:
        shutdown: ["\uf011", "Shut Down"]
        restart: ["\uead2", "Restart"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        sleep: ["\u23fe", "Sleep"]
        cancel: ["", "Cancel"]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      # label: "<span class='icon'>\uf476</span> {count}"
      label: "{count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
